### ISSUE TITLE
Bump `syn` to version 2

### ISSUE THREAD

**Issue by daprilik** [wrenger/bitfield-struct-rs#10]
`syn` recently released version 2.

I'm just auditing all the deps in my Cargo.lock for syn 1, opening issues on projects that haven't switched over yet.

Any chance you could switch over? The quicker everyone moves to version 2, the sooner projects won't have to build both syn 1 and 2 at the same time :)

**Comment by wrenger** [comment]
Ah yes I saw the announcement. I'll update as soon as possible.

**Comment by wrenger** [comment]
Done

**Comment by daprilik** [comment]
Thanks!
