### ISSUE TITLE
u16 bitfield doesn't seem to work right

### ISSUE THREAD

**Issue by OliverGavin** [wrenger/bitfield-struct-rs#13]
I have the following bits I need to parse;
```
0000 10.. .... .... = a: 2
.... ..00 0000 0000 = b: 0
```

I would expect the following to work:
```
#[bitfield(u16)]
pub struct Hdr {
    #[bits(10)]
    pub b: u16,
    #[bits(6)]
    pub a: u16,
}
```

`assert_eq!(hdr.b(), 0);` results in
```
assertion failed: `(left == right)`
  left: `8`,
 right: `0`
```

`assert_eq!(hdr.a(), 2);` results in
```
assertion failed: `(left == right)`
  left: `0`,
 right: `2`
```

I can however get the correct result for `a` if I split up `b` as follows;
```
#[bitfield(u16)]
pub struct Hdr {
    #[bits(2)]
    pub b1: u16,
    #[bits(6)]
    pub a: u16,
    #[bits(8)]
    pub b2: u16,
}
```

That doesn't feel right...
What am I doing wrong?

**Comment by OliverGavin** [comment]
For completeness I could do this with the bitfield crate;

```
bitfield::bitfield!{
    #[derive(Copy, Clone)]
    pub struct Hdr(MSB0 [u8]);
    impl Debug;
    pub u8, a, set_a: 5, 0;
    pub u16, b, set_b: 15, 6;
}
```

Maybe this will help? https://github.com/wrenger/bitfield-struct-rs/issues/12

**Comment by wrenger** [comment]
I'm sorry, but I'm not able to reproduce your problem. The following works as expected:

```rust
#[bitfield(u16)]
pub struct Hdr {
    #[bits(10)]
    pub b: u16,
    #[bits(6)]
    pub a: u16,
}

let hdr = Hdr(0b0000_1000_0000_0000);
assert_eq!(hdr.b(), 0);
assert_eq!(hdr.a(), 2);
```

Or did you do something differently?

**Comment by OliverGavin** [comment]
Hi, maybe I am doing something wrong - this is a simplified version of what I am doing:

```
#[bitfield_struct::bitfield(u16)]
        pub struct Hdr {
            #[bits(10)]
            pub b: u16,
            #[bits(6)]
            pub a: u16,
        }

        let mut bytes = hex!("08 00");
        let hdr: Hdr = unsafe { mem::transmute(bytes) };
        // below fails because of byte order
        assert_eq!(hdr.b(), 0);
        assert_eq!(hdr.a(), 2);
```

I am expecting it to work when using transmute to convert from [u8; 2] to Hdr (i.e. u16).

Based on the below example the endianess seems to be an issue:
```
let mut bytes = hex!("08 00");
let value: u16 = unsafe { mem::transmute(bytes) };
assert_eq!(u16::from_be(value), 0x0800);
```

**Comment by OliverGavin** [comment]
So I think this boils down to the same issue as this: https://github.com/wrenger/bitfield-struct-rs/issues/12

I am using things a bit weird but ultimately `bitfield(u16)` assumes the u16 is already in little endian byte order when I want it to use big endian (or network) byte order.

The weird things I am doing are mostly in my test cases - using transmute. What I am really doing is using this in BPF code where I am getting a pointer, casting it and dereferencing it - either way I am not using your constructor which expects a u16 in little endian byte order.

**Comment by wrenger** [comment]
There are functions for all integers to convert them from and to `[u8; _]` like [u16::from_le](https://doc.rust-lang.org/std/primitive.i16.html#method.from_le).
These are safe and should work independently from your architecture's endianness.

**Comment by OliverGavin** [comment]
yeah I know - just wanted to avoid the unnecessary copy/reshuffle in my BPF code. Currently I am casting bytes of memory to structs for other headers (from C bindings) so I will probably stick to doing that for consistency. So I'll stick to the bitfield crate as it better suits my needs.

Thanks for the help!

**Comment by wrenger** [comment]
No problem, and good luck with your BPF project.
