### ISSUE TITLE
Read-Only Fields

### ISSUE THREAD

**Issue by paul1999** [wrenger/bitfield-struct-rs#27]
I first want to say, I think this crate is great!

I am currently using it for OS development. When writing drivers for some x86 devices, the memory mapped registers used to control the devices sometimes contain read only bits. When programming the device, the register must be read in, other bits may be modified and then the register is written back (as not to modify the read only bits).

It would be useful to me, to be able to mark some members as read only (for example through `[bits(2, read_only = true)]`, where `read_only` would be false by default for backwards compatibility.

I think I could implement that myself (add a field to `Member` and modify `impl ToToken for Member` I guess) but wanted to ask first

**Comment by wrenger** [comment]
Yes, that's correct, especially for x86 it's quite common that certain bits of hardware registers are read-only. For most of the APIC registers you would read the MMIO values, modify certain bits and write back the value (without touching anything read-only).

So I would be happy to accept your contributions if you have the time to help :)

Do we also need write-only? In that case it would make sense to combine this:

```rust
// Default
#[bits(3, access=RW)]
foo: usize,

#[bits(3, access=RO)]
foo: usize,

#[bits(3, access=WO)]
foo: usize,

// Default for padding
#[bits(3, access=None)]
foo: usize,
```
