### ISSUE TITLE
Minor typo in error message

### ISSUE THREAD

**Issue by MarkRoss470** [wrenger/bitfield-struct-rs#29]
The error message when the size of a struct is wrong misspells 'bitfield' as 'bitfiled'. Not an urgent issue but should be an easy fix.

The code for this error message is [here](https://github.com/wrenger/bitfield-struct-rs/blob/c0156c815a43dcd2d83daf14e4c5ee1401c65691/src/lib.rs#L71)

Thanks! This crate is a lifesaver for doing OS development in rust.

**Comment by wrenger** [comment]
Oh yes, thanks for catching this.
