### ISSUE TITLE
Array fields

### ISSUE THREAD

**Issue by NightEule5** [wrenger/bitfield-struct-rs#31]
Currently arrays are not supported as a field type:

```rust
#[bitfield(u128, order = Msb)]
struct LmsState {
    history: [i16; 4],
    weights: [i16; 4]
}
```

This fails, complaining that an explicit bit size is needed. When one is specified, the error becomes `missing angle brackets in associated item path`. The expansion contains `[i16; 4]::from_bits(this)`, which should be `<[i16; 4]>::from_bits(this)`. A workaround is explicitly specifying the conversion, like:

```rust
#[bitfield(u128, order = Msb)]
struct LmsState {
    #[bits(64, from = unpack, into = pack)]
    history: [i16; 4],
    #[bits(64, from = unpack, into = pack)]
    weights: [i16; 4]
}

fn unpack(mut v: u128) -> [i16; 4] {
    let mut r = [0; 4];
    for i in 0..4 {
        r[i] = (v >> 48) as i16;
        v <<= 16;
    }
    r
}

fn pack(v: [i16; 4]) -> u128 {
    v.into_iter().fold(0, |r, v|
        r << 16 | v as u128
    )
}
```

Also, to specify the bit width of an array, it might help to add a way to specify the width of its elements, like:

```rust
#[bitfield(u128, order = Msb)]
struct LmsState {
    #[array_bits(16)]
    history: [i16; 4],
    #[array_bits(16)]
    weights: [i16; 4]
}
```

**Comment by wrenger** [comment]
Solving this is not trivial. The default implementation expects `from_bits` / `into_bits` to be implemented for the custom type. As arrays are not part of your own crate, you cannot implement new const functions for them (only via non-const traits). 
So, fixing this syntax error does not really solve your problem, I guess. You still have to specify other conversion functions with `from` / `into`.
