### ISSUE TITLE
`{from|into}_bits` methods for structs generated by `bitfield`.

### ISSUE THREAD

**Issue by Frostie314159** [wrenger/bitfield-struct-rs#33]
Hi, I wanted to ask, why the functions mentioned in the title aren't automatically generated for structs generated with bitfield.

**Comment by wrenger** [comment]
Solved by yourself 👍🏻  (#34)

**Comment by Frostie314159** [comment]
My project `ieee80211-rs` was stalled on this anyway so I just took matters into my own hands.
