### ISSUE TITLE
Support of raw identifiers

### ISSUE THREAD

**Issue by marcfir** [wrenger/bitfield-struct-rs#35]
It looks like raw identifiers are currently not working. 

I tried `r#type` as a field name, which panicked with
```
custom attribute panicked message: `"with_r#type"` is not a valid identifier
```

**Comment by wrenger** [comment]
Ah this looks like an oversight. Thanks for reporting it.

**Comment by wrenger** [comment]
Seems to be related to: https://github.com/dtolnay/quote/issues/206
I'll change the format_ident calls, respectively.
