### ISSUE TITLE
Document auto-implementation of Copy and Clone traits

### ISSUE THREAD

**Issue by endrift** [wrenger/bitfield-struct-rs#51]
I was porting over from a bitfield library that didn't auto-implement Copy and Clone and ran into errors for every individual struct I ported over. I had already removed Debug and Default, as those are documented to be auto-implemented, but it would have saved me a few minutes to have this documented. It might inherit that from the integer type backed, though, so I'm not sure it's something you manually added.

**Comment by wrenger** [comment]
Oh yes, we defenitely can document which traits are auto-implemented.

**Comment by wrenger** [comment]
Added in 96ad460dade7172de139d8154d439f3d09ac6769 (0.9.1)

**Comment by endrift** [comment]
Thanks!
